### ISSUE TITLE
No elimina correctamente

### ISSUE THREAD

**Issue by gaal1le0** [fjrf16/Exercise-JS-in-DOM#1]
https://github.com/fjrf16/Exercise-JS-in-DOM/blob/ec7170a99e4fe39975e4560dd6114489a1608f3a/src/app.js#L21

Si compruebas el ejercicio en el navegador, cuando yo introduzco el indice a eliminar en el input me elimina siempre el ultimo no el que le indico en el input, eso es por que la referencia que estás pasando no es correcta.
Te recomiendo testarlo en el navegador y verás lo que te comento. Arreglame eso y reenviarme por coreo el enlace cuando este.

**Comment by fjrf16** [comment]
solucionado, era porque lo había hecho en otro fichero y no era este el bueno, ahora está actualizado

**Comment by gaal1le0** [comment]
Recibido :)
